### ISSUE TITLE
Extended flag

### ISSUE THREAD

**Issue by patwin2** [npschafer/openawsem#16]
I was able to successfully run the 1r69 example. However, if I try to run it with the flag --extended I get the following error:

Traceback (most recent call last):
  File "/home/pwintrod/awsem/openawsem/mm_create_project.py", line 97, in <module>
    input_pdb_filename, cleaned_pdb_filename = openmmawsem.prepare_pdb("extended.pdb", "A", use_cis_proline=False, keepIds=args.keepIds, removeHeterogens=removeHeterogens)
  File "/home/pwintrod/awsem/openawsem/openmmawsem.py", line 53, in prepare_pdb
    fixer = PDBFixer(filename=pdb_filename)
  File "/home/pwintrod/anaconda3/envs/sims/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 247, in __init__
    self._initializeFromPDB(file)
  File "/home/pwintrod/anaconda3/envs/sims/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 284, in _initializeFromPDB
    structure = PdbStructure(file)
  File "/home/pwintrod/anaconda3/envs/sims/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbstructure.py", line 152, in __init__
    self._load(input_stream)
  File "/home/pwintrod/anaconda3/envs/sims/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbstructure.py", line 185, in _load
    self._current_model._finalize()
AttributeError: 'NoneType' object has no attribute '_finalize'

**Comment by cabb99** [comment]
It seems that it is working correctly on my end. Did you try the commands in an empty folder or in a folder with a pdb? Was extended.pdb created correctly? Here is the expected output:
```
# In a new empty folder
$ $OPENAWSEM_LOCATION/mm_create_project.py 1r69 --extended
Download from server
Downloading PDB structure '1r69'...
1r69
[<Chain 0>, <Chain 1>]
Chains: A
Chains info read from crystal_structure.pdb, chains to simulate:  A
>CRYSTAL_STRUCTURE:A
63
SISSRVKSKRIQLGLNQAELAQKVGTTQQSIEQLENGKTKRPRFLPELASALGVSVDWLLNGT
protein: 1r69, length: 63
A 63
1r69 project folder created
please modify the force_steps.py if we want to change what energy terms to be used.
```

```
# In a folder with 1r69.pdb
$ $OPENAWSEM_LOCATION/mm_create_project.py ./1r69.pdb --extended
1r69
[<Chain 0>, <Chain 1>]
Chains: A
Chains info read from crystal_structure.pdb, chains to simulate:  A
>CRYSTAL_STRUCTURE:A
63
SISSRVKSKRIQLGLNQAELAQKVGTTQQSIEQLENGKTKRPRFLPELASALGVSVDWLLNGT
protein: 1r69, length: 63
A 63
./1r69.pdb project folder created
please modify the force_steps.py if we want to change what energy terms to be used.
```

**Comment by patwin2** [comment]
OK, it works. It turned out that pymol was installed in the wrong place. When I just deleted and reinstalled it, it runs fine with the extended flag.

Thanks for your help.
